# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# grid_model.py
# Created on: 2018-11-01 14:30:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
worldsq_EA_shp = "C:\\Users\\sr197\\Desktop\\data_prep\\HalfDegreeGrid_GIS\\worldsq_EA.shp"
WDPA_Oct2018_shapefile_polygons_shp = "C:\\Users\\sr197\\Desktop\\data_prep\\WDPA_Oct2018-shapefile\\WDPA_Oct2018-shapefile-polygons.shp"
WDPA_Oct2018_shapefile_polygons__C_M_shp = "C:\\Users\\sr197\\Desktop\\data_prep\\WDPA_Oct2018-shapefile\\WDPA_Oct2018_shapefile_polygons__C_M.shp"
WDPA_Oct2018_shapefile_polygons__C_M_dissolved_shp__2_ = "C:\\Users\\sr197\\Desktop\\data_prep\\WDPA_Oct2018-shapefile\\WDPA_Oct2018_shapefile_polygons__C_M_dissolved.shp"
grid_all_CM_area_dissolved = "C:\\Users\\sr197\\Documents\\ArcGIS\\Projects\\MyProject\\MyProject.gdb\\grid_all_CM_area_dissolved"
WDPA_Oct2018_shapefile_polygons_C_M_notake_shp = "C:\\Users\\sr197\\Desktop\\data_prep\\WDPA_Oct2018-shapefile\\WDPA_Oct2018_shapefile_polygons_C_M_notake.shp"
WDPA_Oct2018_shapefile_polygons__C_M_notake_dissolved_shp__2_ = "C:\\Users\\sr197\\Desktop\\data_prep\\WDPA_Oct2018-shapefile\\WDPA_Oct2018_shapefile_polygons__C_M_notake_dissolved.shp"
grid_no_take_area_dissolved1 = "C:\\Users\\sr197\\Documents\\ArcGIS\\Projects\\MyProject\\MyProject.gdb\\grid_no_take_area_dissolved1"

# Process: Select
##here we are selecting out all of the coastal and marine MPAs
arcpy.Select_analysis(WDPA_Oct2018_shapefile_polygons_shp, WDPA_Oct2018_shapefile_polygons__C_M_shp, "MARINE = '1' Or MARINE = '2'")

# Process: Dissolve (3)
##dissolve the above so that the tabulate intersection won't double count the area of overlapping MPAs
arcpy.Dissolve_management(WDPA_Oct2018_shapefile_polygons__C_M_shp, WDPA_Oct2018_shapefile_polygons__C_M_dissolved_shp__2_, "PA_DEF", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Tabulate Intersection
##this tool calculates the area and percentage of each grid sell that is covered by an MPA and places in a table
arcpy.TabulateIntersection_analysis(worldsq_EA_shp, "Seq", WDPA_Oct2018_shapefile_polygons__C_M_dissolved_shp__2_, grid_all_CM_area_dissolved, "", "", "", "UNKNOWN")


#Repeat for no take MPAs 

# Process: Select (5)
arcpy.Select_analysis(WDPA_Oct2018_shapefile_polygons__C_M_shp, WDPA_Oct2018_shapefile_polygons_C_M_notake_shp, "NO_TAKE = 'All'")

# Process: Dissolve (4)
arcpy.Dissolve_management(WDPA_Oct2018_shapefile_polygons_C_M_notake_shp, WDPA_Oct2018_shapefile_polygons__C_M_notake_dissolved_shp__2_, "PA_DEF", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Tabulate Intersection (2)
arcpy.TabulateIntersection_analysis(worldsq_EA_shp, "Seq", WDPA_Oct2018_shapefile_polygons__C_M_notake_dissolved_shp__2_, grid_no_take_area_dissolved1, "", "", "", "UNKNOWN")

